plugin:
    name: 'kingu.main::lang.plugin.name'
    description: 'kingu.main::lang.plugin.description'
    author: Kingu
    icon: wn-icon-archive
    replaces: {  }
navigation:
    main:
        label: Konten
        url: kingu/main/main
        icon: icon-plug
